language: cpp
compiler: 
    - gcc
adons:
    apt:
        sources:
            -ubuntu-toolchain-r-test
        packages:
            - g++-7.3
install:
    - "[ $CXX = g++ ] && export CXX=g++-7.3 || true"
script:
    make
